# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install .
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m unittest discover -v -b -s tests/
      - store_artifacts:
          path: test-reports
          destination: test-reports
